git:
  depth: 1
language: node_js
node_js:
- '5'
before_script:
- npm install gulp -g
- chmod +x ./deploy-gh-pages.sh
script: "./deploy-gh-pages.sh"
env:
  global:
  - GH_REF: github.com/StreetSupport/streetsupport.net.git
  - secure: pBTmBfBqaks3y0P/KeHTpwfuteMdR9IZJkGJuJM9H6B9Y90qLRfSaQNYRL4SMWyYX0LBT5bjJ4+y8wypjFE7rqbHhExv2NfyJp1q2kTwFQlzMFiy7K2mlu/AsYck0Lk7MmYtsPiEQa6B9ajprDX2+sK8WXgk+GJnn0QB4l/IzWbVGQwYx/tR9PIGNLt2TVOFqnC3aNPgjc4b/QDGpRzOzsfsrI0VM7tvrZIdLc2MBPHpmiw8OaQTBxBKDuo1qa7n0YGgY8yp4EW2wwEW8T6Wa1tTQlApemiZmzYspugXHoOFKgU/Knrt6M2TXui8V4cRetofQG5tH70XpzOUsdE7FtX97sU4mPwuNkFCtZCh/74EZTA4l5LVp8KsiTIRCpN8NUDHUtTO6N+MMjrwieWvJ9wKI4HxRKWPTA5k1NCGnDGmFT6MR4HNecGa7XtKzOaRqht/m2T1zBV+iXmNW0/IhuoNqqKRgqHcq0PdgM4FK1XwM926jX0x7+m080m7eWpkqWo5j1Nsva8qJZq2yQ0Eu9lBBS11omhrQ+9v5Vv7oy1CzjQIxVpWdWnbmb0gfWxGUex6+KGvzhB0VRRhyAgELwPWhiHiwwyLdhN6GQ1Z8YpDhutWFYkah9aAs45MPLvrLA7sVQz0xhEDAqZFyCFCDgXQea/cXmxPuJooGHe5Wzc=
